# Allow KaiOS to fetch the manifest
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[context.production]
  command = "vite build --mode production"

[context.branch-deploy]
  command = "vite build --mode staging"
